name: 'OutlandMusic '
favicon: null
layout_spectrum: 0.56976
typography_spectrum: 0.439967
title: "Nova's World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C8C8'
    - '#781010'
    - '#989898'
    - '#E11E1E'
    - '#000000'
  brandStrength: 0.518092
  lightness: 0.961355
  saturation: 0.084661
  rhythmicContrast: 0.736842
purpose:
  - name: null
    item: null
    url: null
