name: 'OutlandMusic '
favicon: null
layout_spectrum: 0.62034
typography_spectrum: 0.38327
title: "Nova's World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C8C8'
    - '#781010'
    - '#989898'
    - '#E11E1E'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
